# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_userprofile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
