# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_auto_20170209_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
